const now = new Date();
// console.log(now);
console.log(now.toString());
console.log(now.toISOString());
console.log(now.toLocaleString());
console.log(now.getDay());
console.log(now.getDate());
console.log(now.getFullYear());
console.log(now.getHours());
console.log(now.getMinutes());
console.log(now.getSeconds());
console.log(now.getMonth());
